name: Release Example

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Select release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  get-next-version:
    uses: ./.github/workflows/next-version.yml
    with:
      release_type: ${{ inputs.release_type }}
  
  use-version:
    needs: get-next-version
    runs-on: ubuntu-latest
    steps:
      - name: Display selected version
        run: |
          echo "Selected release version: ${{ needs.get-next-version.outputs.release }}"
          echo "Next patch version: ${{ needs.get-next-version.outputs.patch }}"
          echo "Next minor version: ${{ needs.get-next-version.outputs.minor }}"
          echo "Next major version: ${{ needs.get-next-version.outputs.major }}"
      
      - name: Create release (example)
        run: |
          echo "Would create release with version: ${{ needs.get-next-version.outputs.release }}"
          # Here you could add actual release creation logic
          # gh release create ${{ needs.get-next-version.outputs.release }} --title "Release ${{ needs.get-next-version.outputs.release }}"
